name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Init eslint
        run: npx eslint --init

      - name: Check linting
        run: npm install && npm run lint:check
